In [3]:
import torch
import sbi

from sbi.analysis import pairplot
from sbi.inference import NPE
from sbi.utils import BoxUniform
from sbi.utils.user_input_checks import (
    check_sbi_inputs,
    process_prior,
    process_simulator,
)

In [15]:
### Simulate n trees:

# Packages
import gene_model
import gfs
import color_scheme

from matplotlib import pyplot as plt
import seaborn as sns

import sbi
import numpy as np

# Simulation Parameters
theta = 0.2 # Gene Gain rate
rho = 0.04 # Gene Loss rate

gene_conv = 0 # Gene Conversion rate
recomb = 0 # Recombination rate

num_sites = 10 # Number of sites to simulate
num_samples = 5 # Number of samples / individuals

number_of_simulated_data_points = 10

simulated_data_list, parameters_simulation = [], []
for i in range(0, number_of_simulated_data_points):

    hgt_rate = np.random.uniform(0, 0.1) # HGT rate
    
    # Simulate tree:
    mts = gene_model.gene_model(
    theta=theta,
    rho=rho,
    gene_conversion_rate=gene_conv,
    recombination_rate=recomb,
    hgt_rate=hgt_rate,
    num_samples=num_samples,
    num_sites=num_sites,
    double_site_relocation=True, # Fix double gene gain events, won't hide the warning.
    )

    simulated_data_list.append(mts)
    parameters_simulation.append(hgt_rate)




[0 1 3 5 6]
[3 5 6 9]
[0 1 2 4 6]
[2 3 5 8 9]
[0 1 2 3 4 5 6 7 8 9]
[2 9]
[1 4 6 9]
[0 1 2 3 4 6 7 9]
[0 3 7 8]


C:\Users\uhewm\OneDrive\PhD\Project No.2\pangenome-gene-transfer-simulation\gene_model.py:232: RuntimeWarning: 0 double mutation (present -> present) occured. It is recommended to increase the num_sites to 50 or higher. Alternatily use the double_site_relocation or relocate_double_gene_gain option.
  warnings.warn(


[0 1 2 3 4 5 6 7 8 9]


In [21]:
# Read out the simulated data:

simulated_gene_absence_presence_list = []

for i in range(0, number_of_simulated_data_points):
    
    mts = simulated_data_list[i]
    matrix = np.zeros((num_samples, num_sites*2))

    for var in mts.variants():
        if 'present' in var.alleles and 'absent' in var.alleles: # Gene present and absent in different samples
            matrix[:,int(var.site.position)] = var.genotypes
        elif 'present' in var.alleles: # Gene present in all samples
            matrix[:,int(var.site.position)] = np.ones(num_samples)

    simulated_gene_absence_presence_list.append(matrix)

simulated_gene_absence_presence_list[1]

array([[0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

NameError: name 'length' is not defined